//Formatted by ck // pepega tools // cyperdark#6890 // https://github.com/cyperdark/ck-tools
[General]
    Name: - # Re;Asuka v1.0 [NK]
    Author: Nikstrim
    Profile: https://osu.ppy.sh/users/10577559
    ||=====
    || Downloaded from https://ck1t.ru/ss
    || Skin https://ck1t.ru/s-- # Re;Asuka
    ||=====

    edited by zaggernut

    Version: 2.2

// -=- Cursor 
    CursorCentre: 1
    CursorExpand: 0
    CursorRotate: 0

// -=- Misc Settings 
    HitCircleOverlayAboveNumber: 0

// -=- Slider 
    AllowSliderBallTint: 1
    SliderBallFrames: 1
    SliderBallFlip: 1
    SliderStyle: 2

// -=- Spinner 
    SpinnerFrequencyModulate: 1
    SpinnerFadePlayfield: 0
    SpinnerNoBlink: 1

[Colours]
// -=- Combo Colors 
    Combo1: 241,66,106 //red
    Combo2: 255,128,0 //orange
    Combo3: 104,80,218 //purple
    Combo4: 19,189,255 //aqua

// -=- Misc Colors 
    MenuGlow: 0,0,0
    InputOverlayText: 255,255,255

// -=- Slider Colors 
    SliderBorder: 90,90,90  //grey
    ; SliderBorder: 255,69,0  //orange
    SliderTrackOverride: 0,0,0

// -=- Song Select 
    SongSelectActiveText: 255,255,255
    SongSelectInactiveText: 100,100,100

// -=- Colors 
    SpinnerBackground: 60,60,60
    StarBreakAdditive: 255,182,193

[Fonts]
// -=- HitCircle 
    HitCirclePrefix: default
    HitCircleOverlap: 26

// -=- Score 
    ScorePrefix: Assets/font/font
    ScoreOverlap: 6
    ComboPrefix: Assets/score/font
    ComboOverlap: 62